# Generated by Django 5.2.5 on 2025-09-14 01:49

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vehiculos', '0002_remove_vehiculo_estado_actual_remove_vehiculo_tipo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cardex',
            fields=[
                ('id_cardex', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('vehiculo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cardex', to='vehiculos.vehiculo')),
            ],
        ),
        migrations.CreateModel(
            name='RegistroCardex',
            fields=[
                ('id_registro_cardex', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('tipo', models.CharField(choices=[('mantenimiento', 'Mantenimiento'), ('combustible', 'Combustible'), ('otro', 'Otro')], default='otro', max_length=50)),
                ('descripcion', models.TextField()),
                ('documento_respaldo', models.FileField(blank=True, null=True, upload_to='documentos/')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('cardex', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros', to='cardexs.cardex')),
            ],
        ),
    ]
