# Generated by Django 5.2.7 on 2025-10-17 15:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notificaciones', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notificacion',
            options={'ordering': ['-fecha']},
        ),
        migrations.AddIndex(
            model_name='notificacion',
            index=models.Index(fields=['leido', 'fecha'], name='notificacio_leido_39a33d_idx'),
        ),
    ]
