# Generated by Django 5.2.5 on 2025-09-14 01:49

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vehiculos', '0002_remove_vehiculo_estado_actual_remove_vehiculo_tipo_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsumoCombustible',
            fields=[
                ('id_consumo_combustible', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('litros', models.DecimalField(decimal_places=2, max_digits=6)),
                ('costo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estacion', models.CharField(blank=True, max_length=100, null=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('chofer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consumos', to='vehiculos.vehiculo')),
            ],
            options={
                'verbose_name': 'Consumo de combustible',
                'verbose_name_plural': 'Consumos de combustible',
                'db_table': 'consumo_combustible',
            },
        ),
    ]
