# Generated by Django 5.2.7 on 2025-10-17 15:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bitacoras', '0003_alter_bitacora_options_and_more'),
        ('consumos_combustible', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='consumocombustible',
            options={'ordering': ['-fecha'], 'verbose_name': 'Consumo de combustible', 'verbose_name_plural': 'Consumos de combustible'},
        ),
        migrations.AddField(
            model_name='consumocombustible',
            name='bitacora',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consumo', to='bitacoras.bitacora'),
        ),
        migrations.AlterField(
            model_name='consumocombustible',
            name='costo',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='consumocombustible',
            name='litros',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
    ]
