# Generated by Django 5.2.5 on 2025-09-14 01:49

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bitacoras', '0001_initial'),
        ('vehiculos', '0002_remove_vehiculo_estado_actual_remove_vehiculo_tipo_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bitacora',
            fields=[
                ('id_bitacora', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('km_inicial', models.PositiveIntegerField()),
                ('km_final', models.PositiveIntegerField()),
                ('combustible_cargado', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('costo_combustible', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('foto_odometro_inicio', models.ImageField(blank=True, null=True, upload_to='odometros/')),
                ('foto_odometro_fin', models.ImageField(blank=True, null=True, upload_to='odometros/')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('chofer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bitacoras', to='vehiculos.vehiculo')),
            ],
            options={
                'verbose_name': 'Bitacora',
                'verbose_name_plural': 'Bitacoras',
                'db_table': 'bitacora',
            },
        ),
        migrations.DeleteModel(
            name='BitacoraViaje',
        ),
    ]
