# Generated by Django 5.2.7 on 2025-10-17 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bitacoras', '0002_bitacora_delete_bitacoraviaje'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bitacora',
            options={'ordering': ['-fecha'], 'verbose_name': 'Bitácora', 'verbose_name_plural': 'Bitácoras'},
        ),
        migrations.AlterField(
            model_name='bitacora',
            name='combustible_cargado',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='bitacora',
            name='costo_combustible',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
