# Generated by Django 5.2.7 on 2025-10-18 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bitacoras', '0003_alter_bitacora_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bitacora',
            name='foto_odometro_fin',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bitacora',
            name='foto_odometro_inicio',
            field=models.URLField(blank=True, null=True),
        ),
    ]
