# Generated by Django 5.1.2 on 2024-12-17 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_alter_usuario_rol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('Gerente', 'Gerente'), ('Administrador', 'Administrador'), ('Ventas', 'Ventas'), ('Logistica', 'Logistica'), ('Cocina', 'Cocina'), ('Delivery', 'Delivery')], default='Delivery', max_length=20),
        ),
    ]
