# Generated by Django 5.1.2 on 2025-01-10 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_alter_usuario_rol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('Administrador', 'Administrador'), ('Cocina', 'Cocina'), ('Delivery', 'Delivery')], default='Delivery', max_length=20),
        ),
    ]
