# Generated by Django 5.2.1 on 2025-06-08 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_alter_usuario_rol'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='ci',
        ),
    ]
