# Generated by Django 5.2.1 on 2025-06-08 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_remove_usuario_ci'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('Administrador', 'Administrador'), ('Tecnico', 'Tecnico'), ('Conductor', 'Conductor')], default='Conductor', max_length=20),
        ),
    ]
