# Generated by Django 5.2.5 on 2025-09-14 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0006_alter_usuario_rol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('Administrador general', 'Administrador general'), ('Jefe de unidad', 'Jefe de unidad'), ('Encargado parque motor', 'Encargado parque motor'), ('Chofer', 'Chofer'), ('Finanzas', 'Finanzas')], default='Chofer', max_length=30),
        ),
    ]
