# Generated by Django 5.2.5 on 2025-09-14 01:49

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mantenimientos', '0002_solicitudmantenimiento_ordenservicio_and_more'),
        ('repuestos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='repuesto',
            name='codigo',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='repuesto',
            name='precio_unitario',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.CreateModel(
            name='DevolucionRepuesto',
            fields=[
                ('id_devolucion_repuesto', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cantidad', models.PositiveIntegerField()),
                ('fecha', models.DateField(auto_now_add=True)),
                ('observacion', models.TextField(blank=True, null=True)),
                ('orden_servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devoluciones', to='mantenimientos.ordenservicio')),
                ('repuesto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='repuestos.repuesto')),
            ],
        ),
        migrations.CreateModel(
            name='RepuestoUsado',
            fields=[
                ('id_repuesto_usado', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('orden_servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalle_repuestos', to='mantenimientos.ordenservicio')),
                ('repuesto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='repuestos.repuesto')),
            ],
        ),
    ]
