# Generated by Django 5.2.7 on 2025-10-17 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repuestos', '0002_repuesto_codigo_repuesto_precio_unitario_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='repuesto',
            options={'ordering': ['nombre'], 'verbose_name': 'Repuesto', 'verbose_name_plural': 'Repuestos'},
        ),
        migrations.AlterField(
            model_name='repuesto',
            name='precio_unitario',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='repuestousado',
            name='precio_unitario',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
    ]
