# Generated by Django 5.2.1 on 2025-06-03 23:25

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vehiculos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DotacionCombustible',
            fields=[
                ('id_dotacion_combustible', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('cantidad_litros', models.FloatField()),
                ('kilometraje_actual', models.FloatField()),
                ('observaciones', models.TextField(blank=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehiculos.vehiculo')),
            ],
            options={
                'verbose_name': 'Dotacion Combustible',
                'verbose_name_plural': 'Dotaciones de Combustible',
                'db_table': 'dotacion_combustible',
            },
        ),
    ]
