# Generated by Django 5.2.7 on 2025-10-17 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculos', '0002_remove_vehiculo_estado_actual_remove_vehiculo_tipo_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='asignacionvehiculo',
            options={'verbose_name': 'Asignación de Vehículo', 'verbose_name_plural': 'Asignaciones de Vehículos'},
        ),
        migrations.AlterModelOptions(
            name='vehiculo',
            options={'ordering': ['placa'], 'verbose_name': 'Vehículo', 'verbose_name_plural': 'Vehículos'},
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='anio',
            field=models.PositiveIntegerField(),
        ),
    ]
