# Generated by Django 5.2.7 on 2025-10-17 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculos', '0003_alter_asignacionvehiculo_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiculo',
            name='departamento',
            field=models.CharField(choices=[('LP', 'La Paz'), ('CB', 'Cochabamba'), ('SC', 'Santa Cruz'), ('OR', 'Oruro'), ('PT', 'Potosí'), ('CH', 'Chuquisaca'), ('TJ', 'Tarija'), ('BN', 'Beni'), ('PD', 'Pando')], default='LP', max_length=2),
        ),
    ]
