# Generated by Django 5.2.7 on 2025-10-17 16:20

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculos', '0004_vehiculo_departamento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asignacionvehiculo',
            name='fecha_inicio',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
