# Generated by Django 5.2.5 on 2025-09-14 01:49

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mantenimientos', '0001_initial'),
        ('vehiculos', '0002_remove_vehiculo_estado_actual_remove_vehiculo_tipo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitudMantenimiento',
            fields=[
                ('id_solicitud_mantenimiento', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fecha_solicitud', models.DateField(auto_now_add=True)),
                ('descripcion', models.TextField()),
                ('tipo', models.CharField(choices=[('aceite', 'Cambio de aceite'), ('frenos', 'Frenos'), ('suspension', 'Suspensión'), ('llantas', 'Llantas'), ('bateria', 'Batería'), ('otro', 'Otro')], default='otro', max_length=50)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobado', 'Aprobado'), ('finalizado', 'Finalizado')], default='pendiente', max_length=20)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes', to='vehiculos.vehiculo')),
            ],
            options={
                'verbose_name': 'Solicitud de Mantenimiento',
                'verbose_name_plural': 'Solicitudes de Mantenimientos',
                'db_table': 'solicitud_mantenimiento',
            },
        ),
        migrations.CreateModel(
            name='OrdenServicio',
            fields=[
                ('id_orden_servicio', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fecha_emision', models.DateField(auto_now_add=True)),
                ('proveedor', models.CharField(max_length=100)),
                ('costo_mano_obra', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('costo_aceites', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('solicitud', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='orden_servicio', to='mantenimientos.solicitudmantenimiento')),
            ],
        ),
        migrations.DeleteModel(
            name='Mantenimiento',
        ),
    ]
