# Generated by Django 5.2.7 on 2025-10-17 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mantenimientos', '0002_solicitudmantenimiento_ordenservicio_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ordenservicio',
            options={'ordering': ['-fecha_emision'], 'verbose_name': 'Orden de servicio', 'verbose_name_plural': 'Órdenes de servicio'},
        ),
        migrations.AlterModelOptions(
            name='solicitudmantenimiento',
            options={'ordering': ['-fecha_solicitud'], 'verbose_name': 'Solicitud de mantenimiento', 'verbose_name_plural': 'Solicitudes de mantenimiento'},
        ),
        migrations.AlterField(
            model_name='ordenservicio',
            name='costo_aceites',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='ordenservicio',
            name='costo_mano_obra',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterModelTable(
            name='ordenservicio',
            table='orden_servicio',
        ),
    ]
